"""固定互联网企业办公文档 taxonomy。"""

from typing import Any


def _label(
    *,
    label_id: str,
    path: list[str],
    label: str,
    aliases: list[str],
    keywords: list[str],
    negative_keywords: list[str],
    file_types: list[str],
) -> dict[str, Any]:
    return {
        "id": label_id,
        "path": path,
        "label": label,
        "aliases": aliases,
        "keywords": keywords,
        "negative_keywords": negative_keywords,
        "file_types": file_types,
    }


TAXONOMY = {
    "human_resources": {
        "display": "人力资源",
        "labels": [
            {
                "id": "hr.recruitment",
                "path": ["人力资源", "招聘管理", "招聘需求"],
                "label": "招聘需求",
                "aliases": ["用人申请", "人员需求", "HC申请"],
                "keywords": ["岗位", "职责", "招聘", "HC", "人员需求", "候选人", "JD"],
                "negative_keywords": ["报销", "合同", "发票"],
                "file_types": [".docx", ".pdf"],
            },
            {
                "id": "hr.offer_approval",
                "path": ["人力资源", "招聘管理", "Offer审批"],
                "label": "Offer审批",
                "aliases": ["录用审批", "薪资审批", "offer审批"],
                "keywords": ["候选人", "录用", "薪资包", "职级", "offer", "入职日期"],
                "negative_keywords": ["绩效", "报销"],
                "file_types": [".docx", ".pdf", ".xlsx"],
            },
            {
                "id": "hr.onboarding",
                "path": ["人力资源", "入职管理", "入职材料"],
                "label": "入职材料",
                "aliases": ["入职资料", "新员工手册"],
                "keywords": ["入职", "新员工", "试用期", "报到", "培训"],
                "negative_keywords": ["离职", "报销"],
                "file_types": [".docx", ".pdf"],
            },
            {
                "id": "hr.performance",
                "path": ["人力资源", "绩效管理", "绩效考核"],
                "label": "绩效考核",
                "aliases": ["绩效评估", "KPI考核", "OKR"],
                "keywords": ["绩效", "KPI", "OKR", "评分", "考核", "目标"],
                "negative_keywords": ["招聘", "薪资"],
                "file_types": [".docx", ".pdf", ".xlsx"],
            },
            _label(
                label_id="hr.training",
                path=["人力资源", "培训发展", "培训计划"],
                label="培训计划",
                aliases=["培训安排", "课程计划", "培养计划"],
                keywords=["培训", "课程", "讲师", "学习地图", "培养", "内训"],
                negative_keywords=["离职", "报销", "采购"],
                file_types=[".docx", ".pdf", ".pptx"],
            ),
            _label(
                label_id="hr.offboarding",
                path=["人力资源", "员工关系", "离职办理"],
                label="离职办理",
                aliases=["离职交接", "离职审批", "离任流程"],
                keywords=["离职", "交接", "离任", "工作交接", "最后工作日", "归还资产"],
                negative_keywords=["入职", "招聘", "offer"],
                file_types=[".docx", ".pdf", ".xlsx"],
            ),
        ],
    },
    "finance": {
        "display": "财务管理",
        "labels": [
            {
                "id": "finance.expense",
                "path": ["财务管理", "报销管理", "费用报销"],
                "label": "费用报销",
                "aliases": ["报销申请", "差旅报销", "费用单"],
                "keywords": ["报销", "费用", "发票", "单据", "出差"],
                "negative_keywords": ["采购合同", "预算申请"],
                "file_types": [".xlsx", ".pdf", ".docx"],
            },
            {
                "id": "finance.budget",
                "path": ["财务管理", "预算管理", "预算申请"],
                "label": "预算申请",
                "aliases": ["费用预算", "年度预算"],
                "keywords": ["预算", "费用计划", "年度", "季度", "资金"],
                "negative_keywords": ["报销", "发票"],
                "file_types": [".xlsx", ".docx"],
            },
            {
                "id": "finance.payment",
                "path": ["财务管理", "付款管理", "付款审批"],
                "label": "付款审批",
                "aliases": ["打款申请", "付款单"],
                "keywords": ["付款", "打款", "转账", "应付", "供应商"],
                "negative_keywords": ["报销", "工资"],
                "file_types": [".docx", ".pdf"],
            },
            _label(
                label_id="finance.invoice",
                path=["财务管理", "票据管理", "发票台账"],
                label="发票台账",
                aliases=["票据台账", "发票登记", "开票记录"],
                keywords=["发票", "票据", "开票", "税号", "抬头", "台账"],
                negative_keywords=["合同", "招聘", "培训"],
                file_types=[".xlsx", ".pdf"],
            ),
            _label(
                label_id="finance.monthly_report",
                path=["财务管理", "财务分析", "财务月报"],
                label="财务月报",
                aliases=["月度财报", "经营月报", "财务分析"],
                keywords=["月报", "收入", "利润", "成本", "现金流", "财务分析"],
                negative_keywords=["报销", "招聘", "法务"],
                file_types=[".xlsx", ".pptx", ".pdf"],
            ),
            _label(
                label_id="finance.tax",
                path=["财务管理", "税务管理", "税务申报"],
                label="税务申报",
                aliases=["纳税申报", "税务资料", "税务申报表"],
                keywords=["税务", "纳税", "增值税", "申报", "税率", "汇算"],
                negative_keywords=["报销", "预算", "采购"],
                file_types=[".xlsx", ".pdf", ".docx"],
            ),
        ],
    },
    "legal": {
        "display": "法务合规",
        "labels": [
            {
                "id": "legal.contract",
                "path": ["法务合规", "合同管理", "标准合同"],
                "label": "标准合同",
                "aliases": ["合同模板", "协议模板"],
                "keywords": ["合同", "协议", "甲方", "乙方", "签约", "盖章"],
                "negative_keywords": ["发票", "报销"],
                "file_types": [".docx", ".pdf"],
            },
            {
                "id": "legal.review",
                "path": ["法务合规", "合同管理", "法务审查"],
                "label": "法务审查",
                "aliases": ["合同审查", "法律意见"],
                "keywords": ["审查", "法务", "风险", "条款", "意见"],
                "negative_keywords": [],
                "file_types": [".docx", ".pdf"],
            },
            {
                "id": "legal.compliance",
                "path": ["法务合规", "合规管理", "合规制度"],
                "label": "合规制度",
                "aliases": ["内控制度", "合规规定"],
                "keywords": ["合规", "规定", "制度", "内控", "监管"],
                "negative_keywords": [],
                "file_types": [".docx", ".pdf"],
            },
            _label(
                label_id="legal.authorization",
                path=["法务合规", "授权管理", "授权文件"],
                label="授权文件",
                aliases=["授权书", "委托授权", "签字授权"],
                keywords=["授权", "委托", "授权书", "签字", "法定代表人", "代理"],
                negative_keywords=["报销", "预算"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="legal.privacy",
                path=["法务合规", "数据合规", "隐私条款"],
                label="隐私条款",
                aliases=["隐私政策", "个人信息条款", "数据合规条款"],
                keywords=["隐私", "个人信息", "数据处理", "授权同意", "条款", "信息保护"],
                negative_keywords=["报销", "采购"],
                file_types=[".docx", ".pdf", ".md"],
            ),
            _label(
                label_id="legal.ip",
                path=["法务合规", "知识产权", "知识产权"],
                label="知识产权",
                aliases=["商标资料", "专利文件", "著作权申请"],
                keywords=["商标", "专利", "著作权", "知识产权", "侵权", "申请"],
                negative_keywords=["发票", "报销"],
                file_types=[".docx", ".pdf"],
            ),
        ],
    },
    "product": {
        "display": "产品管理",
        "labels": [
            {
                "id": "product.prd",
                "path": ["产品管理", "需求管理", "需求文档"],
                "label": "需求文档",
                "aliases": ["PRD", "产品需求", "功能需求"],
                "keywords": ["需求", "PRD", "功能", "用户故事", "验收", "原型"],
                "negative_keywords": ["测试报告", "上线变更"],
                "file_types": [".docx", ".pdf"],
            },
            {
                "id": "product.release",
                "path": ["产品管理", "版本管理", "发布说明"],
                "label": "发布说明",
                "aliases": ["Release Note", "版本说明", "更新日志"],
                "keywords": ["发布", "版本", "更新", "changelog", "release"],
                "negative_keywords": [],
                "file_types": [".docx", ".pdf", ".md"],
            },
            _label(
                label_id="product.roadmap",
                path=["产品管理", "版本管理", "版本规划"],
                label="版本规划",
                aliases=["Roadmap", "路线图", "迭代规划"],
                keywords=["规划", "路线图", "roadmap", "里程碑", "版本", "排期"],
                negative_keywords=["报价", "合同"],
                file_types=[".docx", ".pptx", ".xlsx"],
            ),
            _label(
                label_id="product.research",
                path=["产品管理", "用户研究", "用户调研"],
                label="用户调研",
                aliases=["用户访谈", "问卷分析", "用户研究"],
                keywords=["用户", "访谈", "调研", "问卷", "画像", "痛点"],
                negative_keywords=["测试用例", "合同"],
                file_types=[".docx", ".pdf", ".pptx"],
            ),
            _label(
                label_id="product.competitor",
                path=["产品管理", "市场研究", "竞品分析"],
                label="竞品分析",
                aliases=["竞品研究", "同类产品分析", "对标分析"],
                keywords=["竞品", "对标", "产品分析", "功能对比", "差异化", "市场格局"],
                negative_keywords=["发票", "报销"],
                file_types=[".docx", ".pptx", ".pdf"],
            ),
            _label(
                label_id="product.acceptance",
                path=["产品管理", "交付管理", "验收清单"],
                label="验收清单",
                aliases=["验收项", "交付验收", "验收标准"],
                keywords=["验收", "交付", "清单", "上线验收", "完成标准", "交付物"],
                negative_keywords=["招聘", "报销"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
        ],
    },
    "procurement": {
        "display": "采购供应链",
        "labels": [
            _label(
                label_id="procurement.request",
                path=["采购供应链", "采购管理", "采购需求"],
                label="采购需求",
                aliases=["采购申请", "请购单", "采购立项"],
                keywords=["采购", "需求", "请购", "设备", "数量", "供应商"],
                negative_keywords=["报销", "招聘", "绩效"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="procurement.vendor_evaluation",
                path=["采购供应链", "供应商管理", "供应商评估"],
                label="供应商评估",
                aliases=["供应商审核", "供应商准入", "vendor评估"],
                keywords=["供应商", "评估", "准入", "资质", "评分", "交付能力"],
                negative_keywords=["发票", "薪资"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="procurement.contract_order",
                path=["采购供应链", "订单合同", "合同订单"],
                label="合同订单",
                aliases=["采购合同", "采购订单", "PO"],
                keywords=["订单", "PO", "采购合同", "交付", "条款", "采购金额"],
                negative_keywords=["报销", "offer"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="procurement.receipt_inspection",
                path=["采购供应链", "仓储履约", "入库验收"],
                label="入库验收",
                aliases=["到货验收", "收货单", "入库单"],
                keywords=["入库", "验收", "到货", "收货", "仓库", "质检"],
                negative_keywords=["报销", "税务"],
                file_types=[".xlsx", ".pdf", ".docx"],
            ),
            _label(
                label_id="procurement.bid_comparison",
                path=["采购供应链", "供应商管理", "招标比价"],
                label="招标比价",
                aliases=["询价比价", "招标文件", "比价表"],
                keywords=["招标", "比价", "询价", "报价单", "中标", "评分"],
                negative_keywords=["工资", "绩效"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
            _label(
                label_id="procurement.statement",
                path=["采购供应链", "采购分析", "采购台账"],
                label="采购台账",
                aliases=["采购清单", "采购明细", "采购月报"],
                keywords=["采购台账", "明细", "采购金额", "供应商", "统计", "月报"],
                negative_keywords=["报销", "绩效"],
                file_types=[".xlsx", ".csv", ".pdf"],
            ),
        ],
    },
    "sales": {
        "display": "销售商务",
        "labels": [
            _label(
                label_id="sales.proposal",
                path=["销售商务", "商机推进", "销售方案"],
                label="销售方案",
                aliases=["售前方案", "解决方案", "提案方案"],
                keywords=["方案", "客户", "需求匹配", "解决方案", "售前", "价值点"],
                negative_keywords=["测试用例", "报销"],
                file_types=[".pptx", ".docx", ".pdf"],
            ),
            _label(
                label_id="sales.quotation",
                path=["销售商务", "商务报价", "商务报价"],
                label="商务报价",
                aliases=["报价单", "报价方案", "价格清单"],
                keywords=["报价", "价格", "折扣", "商务", "套餐", "金额"],
                negative_keywords=["报销", "发票台账"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
            _label(
                label_id="sales.contract",
                path=["销售商务", "合同管理", "销售合同"],
                label="销售合同",
                aliases=["商务合同", "客户合同", "合作协议"],
                keywords=["合同", "客户", "签约", "回款", "条款", "合作"],
                negative_keywords=["采购合同", "报销"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="sales.visit_log",
                path=["销售商务", "客户管理", "拜访记录"],
                label="拜访记录",
                aliases=["客户拜访", "访谈纪要", "跟进记录"],
                keywords=["拜访", "客户", "跟进", "会议纪要", "需求", "行动项"],
                negative_keywords=["项目复盘", "故障复盘"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="sales.monthly_report",
                path=["销售商务", "经营分析", "销售月报"],
                label="销售月报",
                aliases=["销售周报", "业绩月报", "销售分析"],
                keywords=["销售", "业绩", "月报", "线索", "签约", "回款"],
                negative_keywords=["财务月报", "审计报告"],
                file_types=[".xlsx", ".pptx", ".pdf"],
            ),
            _label(
                label_id="sales.tender_response",
                path=["销售商务", "投标管理", "投标应答"],
                label="投标应答",
                aliases=["标书应答", "投标文件", "招投标"],
                keywords=["投标", "标书", "应答", "招标", "应标", "资质"],
                negative_keywords=["采购需求", "发票"],
                file_types=[".docx", ".pdf", ".pptx"],
            ),
        ],
    },
    "marketing": {
        "display": "市场品牌",
        "labels": [
            _label(
                label_id="marketing.strategy",
                path=["市场品牌", "市场策划", "市场方案"],
                label="市场方案",
                aliases=["市场计划", "营销方案", "传播方案"],
                keywords=["市场", "方案", "传播", "用户增长", "渠道", "预算"],
                negative_keywords=["测试用例", "报销"],
                file_types=[".pptx", ".docx", ".pdf"],
            ),
            _label(
                label_id="marketing.event",
                path=["市场品牌", "活动运营", "活动策划"],
                label="活动策划",
                aliases=["活动方案", "campaign策划", "活动执行"],
                keywords=["活动", "策划", "campaign", "会场", "物料", "执行"],
                negative_keywords=["会议安排", "项目计划"],
                file_types=[".pptx", ".docx", ".xlsx"],
            ),
            _label(
                label_id="marketing.brand_guideline",
                path=["市场品牌", "品牌管理", "品牌规范"],
                label="品牌规范",
                aliases=["品牌手册", "视觉规范", "品牌指南"],
                keywords=["品牌", "规范", "VI", "logo", "字体", "色值"],
                negative_keywords=["合同", "报销"],
                file_types=[".pdf", ".pptx", ".docx"],
            ),
            _label(
                label_id="marketing.competitor",
                path=["市场品牌", "市场研究", "竞品分析"],
                label="竞品分析",
                aliases=["对手分析", "竞对分析", "市场对标"],
                keywords=["竞品", "竞对", "对标", "份额", "策略", "分析"],
                negative_keywords=["财务月报", "审计报告"],
                file_types=[".pptx", ".docx", ".pdf"],
            ),
            _label(
                label_id="marketing.asset",
                path=["市场品牌", "内容资产", "推广素材"],
                label="推广素材",
                aliases=["广告物料", "宣传素材", "投放素材"],
                keywords=["素材", "海报", "banner", "落地页", "文案", "推广"],
                negative_keywords=["用印申请", "报销"],
                file_types=[".pptx", ".pdf", ".docx"],
            ),
            _label(
                label_id="marketing.content_calendar",
                path=["市场品牌", "内容运营", "内容计划"],
                label="内容计划",
                aliases=["内容日历", "选题计划", "内容排期"],
                keywords=["内容", "选题", "排期", "公众号", "稿件", "发布节奏"],
                negative_keywords=["发布说明", "上线变更"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
        ],
    },
    "customer_service": {
        "display": "客户服务",
        "labels": [
            _label(
                label_id="customer_service.manual",
                path=["客户服务", "服务体系", "服务手册"],
                label="服务手册",
                aliases=["客服手册", "服务指南", "支持手册"],
                keywords=["服务手册", "客服", "流程", "处理规范", "服务标准", "话术"],
                negative_keywords=["测试用例", "产品需求"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="customer_service.complaint",
                path=["客户服务", "投诉处理", "投诉记录"],
                label="投诉记录",
                aliases=["客诉记录", "投诉单", "投诉处理"],
                keywords=["投诉", "客诉", "升级", "处理结果", "服务问题", "反馈"],
                negative_keywords=["绩效", "报销"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="customer_service.feedback",
                path=["客户服务", "客户声音", "客户反馈"],
                label="客户反馈",
                aliases=["用户反馈", "客户建议", "满意度反馈"],
                keywords=["反馈", "客户建议", "满意度", "使用问题", "建议", "体验"],
                negative_keywords=["测试计划", "发布说明"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
            _label(
                label_id="customer_service.sla",
                path=["客户服务", "服务协议", "SLA协议"],
                label="SLA协议",
                aliases=["服务级别协议", "支持协议", "服务承诺"],
                keywords=["SLA", "服务级别", "响应时间", "可用性", "支持等级", "协议"],
                negative_keywords=["采购合同", "报销"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="customer_service.ticket_report",
                path=["客户服务", "工单运营", "工单周报"],
                label="工单周报",
                aliases=["工单月报", "支持分析", "客服周报"],
                keywords=["工单", "周报", "月报", "解决率", "响应时长", "工单量"],
                negative_keywords=["销售月报", "财务月报"],
                file_types=[".xlsx", ".pptx", ".pdf"],
            ),
            _label(
                label_id="customer_service.knowledge_base",
                path=["客户服务", "知识体系", "知识库文章"],
                label="知识库文档",
                aliases=["FAQ文档", "帮助中心", "知识库文章"],
                keywords=["FAQ", "帮助中心", "操作说明", "问题解答", "知识库", "常见问题"],
                negative_keywords=["法律意见", "报销"],
                file_types=[".docx", ".md", ".pdf"],
            ),
        ],
    },
    "engineering": {
        "display": "研发工程",
        "labels": [
            _label(
                label_id="engineering.tech_design",
                path=["研发工程", "技术设计", "技术方案"],
                label="技术方案",
                aliases=["方案设计", "技术选型", "实现方案"],
                keywords=["技术方案", "设计", "选型", "实现", "架构", "模块"],
                negative_keywords=["产品需求", "测试报告"],
                file_types=[".docx", ".md", ".pdf"],
            ),
            _label(
                label_id="engineering.api",
                path=["研发工程", "接口管理", "接口文档"],
                label="接口文档",
                aliases=["API文档", "接口说明", "Swagger说明"],
                keywords=["接口", "API", "请求", "响应", "参数", "鉴权"],
                negative_keywords=["合同", "报销"],
                file_types=[".docx", ".md", ".pdf"],
            ),
            _label(
                label_id="engineering.architecture",
                path=["研发工程", "技术设计", "架构设计"],
                label="架构设计",
                aliases=["系统架构", "架构方案", "技术架构"],
                keywords=["架构", "系统设计", "高可用", "服务拆分", "组件", "技术架构"],
                negative_keywords=["测试用例", "竞品分析"],
                file_types=[".docx", ".md", ".pdf", ".pptx"],
            ),
            _label(
                label_id="engineering.dev_spec",
                path=["研发工程", "工程规范", "开发规范"],
                label="开发规范",
                aliases=["编码规范", "研发规范", "代码规范"],
                keywords=["规范", "编码", "提交", "分支", "review", "开发流程"],
                negative_keywords=["法律法规", "报销"],
                file_types=[".docx", ".md", ".pdf"],
            ),
            _label(
                label_id="engineering.postmortem",
                path=["研发工程", "故障管理", "故障复盘"],
                label="故障复盘",
                aliases=["事故复盘", "故障分析", "postmortem"],
                keywords=["故障", "事故", "复盘", "根因", "恢复", "影响范围"],
                negative_keywords=["项目复盘", "会议纪要"],
                file_types=[".docx", ".md", ".pdf"],
            ),
            _label(
                label_id="engineering.release_change",
                path=["研发工程", "发布运维", "上线变更"],
                label="上线变更",
                aliases=["变更单", "上线申请", "发布变更"],
                keywords=["上线", "变更", "发布", "回滚", "窗口期", "影响评估"],
                negative_keywords=["发布说明", "活动策划"],
                file_types=[".docx", ".md", ".pdf"],
            ),
        ],
    },
    "qa": {
        "display": "测试质量",
        "labels": [
            _label(
                label_id="qa.test_plan",
                path=["测试质量", "测试管理", "测试计划"],
                label="测试计划",
                aliases=["测试方案", "测试安排", "测试策略"],
                keywords=["测试计划", "测试范围", "资源安排", "里程碑", "风险", "策略"],
                negative_keywords=["产品需求", "报销"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="qa.test_case",
                path=["测试质量", "测试设计", "测试用例"],
                label="测试用例",
                aliases=["case清单", "测试案例", "测试点"],
                keywords=["用例", "步骤", "预期结果", "前置条件", "测试点", "场景"],
                negative_keywords=["需求文档", "竞品分析"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
            _label(
                label_id="qa.bug_report",
                path=["测试质量", "缺陷管理", "缺陷报告"],
                label="缺陷报告",
                aliases=["bug报告", "问题单", "缺陷单"],
                keywords=["缺陷", "bug", "复现步骤", "严重级别", "影响", "问题单"],
                negative_keywords=["投诉记录", "合同"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="qa.quality_report",
                path=["测试质量", "质量分析", "质量报告"],
                label="质量报告",
                aliases=["测试报告", "质量周报", "质量分析"],
                keywords=["质量", "测试报告", "通过率", "缺陷率", "稳定性", "覆盖率"],
                negative_keywords=["销售月报", "财务月报"],
                file_types=[".pptx", ".docx", ".pdf"],
            ),
            _label(
                label_id="qa.regression",
                path=["测试质量", "测试执行", "回归测试"],
                label="回归测试",
                aliases=["回归报告", "回归验证", "冒烟测试"],
                keywords=["回归", "冒烟", "验证", "回归测试", "发布验证", "覆盖"],
                negative_keywords=["发布说明", "上线申请"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="qa.acceptance",
                path=["测试质量", "交付验证", "验收测试"],
                label="验收测试",
                aliases=["UAT", "用户验收", "验收报告"],
                keywords=["验收测试", "UAT", "验收", "签收", "交付验证", "用户验收"],
                negative_keywords=["采购验收", "入库验收"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
        ],
    },
    "data": {
        "display": "数据分析",
        "labels": [
            _label(
                label_id="data.requirement",
                path=["数据分析", "需求管理", "数据需求"],
                label="数据需求",
                aliases=["数仓需求", "报表需求", "埋点需求"],
                keywords=["数据需求", "报表", "埋点", "指标", "分析诉求", "取数"],
                negative_keywords=["产品需求", "招聘需求"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="data.analysis_report",
                path=["数据分析", "分析研究", "分析报告"],
                label="分析报告",
                aliases=["数据分析", "经营分析", "专题分析"],
                keywords=["分析", "数据", "趋势", "结论", "洞察", "样本"],
                negative_keywords=["审计报告", "测试报告"],
                file_types=[".pptx", ".docx", ".pdf"],
            ),
            _label(
                label_id="data.metric_definition",
                path=["数据分析", "指标管理", "指标定义"],
                label="指标定义",
                aliases=["指标口径", "口径说明", "指标说明"],
                keywords=["指标", "口径", "定义", "统计规则", "维度", "计算逻辑"],
                negative_keywords=["预算申请", "合同"],
                file_types=[".docx", ".md", ".pdf"],
            ),
            _label(
                label_id="data.dictionary",
                path=["数据分析", "数据治理", "数据字典"],
                label="数据字典",
                aliases=["字段字典", "表结构说明", "字典文档"],
                keywords=["数据字典", "字段", "表结构", "类型", "枚举", "元数据"],
                negative_keywords=["接口文档", "架构设计"],
                file_types=[".xlsx", ".docx", ".md"],
            ),
            _label(
                label_id="data.dashboard",
                path=["数据分析", "数据产品", "看板说明"],
                label="看板说明",
                aliases=["Dashboard说明", "看板口径", "报表说明"],
                keywords=["看板", "dashboard", "报表说明", "图表", "刷新频率", "口径"],
                negative_keywords=["品牌规范", "发布说明"],
                file_types=[".docx", ".pptx", ".pdf"],
            ),
            _label(
                label_id="data.modeling",
                path=["数据分析", "数据治理", "建模方案"],
                label="建模方案",
                aliases=["数仓建模", "主题域设计", "模型设计"],
                keywords=["建模", "主题域", "事实表", "维度表", "数仓", "模型"],
                negative_keywords=["招聘", "报销"],
                file_types=[".docx", ".md", ".pdf"],
            ),
        ],
    },
    "ops": {
        "display": "运维安全",
        "labels": [
            _label(
                label_id="ops.runbook",
                path=["运维安全", "运维体系", "运维手册"],
                label="运维手册",
                aliases=["操作手册", "运行手册", "运维指南"],
                keywords=["运维", "手册", "操作步骤", "运行", "巡检", "恢复"],
                negative_keywords=["客服手册", "品牌手册"],
                file_types=[".docx", ".md", ".pdf"],
            ),
            _label(
                label_id="ops.change_request",
                path=["运维安全", "变更管理", "变更申请"],
                label="变更申请",
                aliases=["变更单", "运维变更", "变更审批"],
                keywords=["变更", "申请", "窗口期", "影响评估", "回滚", "上线"],
                negative_keywords=["预算申请", "采购申请"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="ops.security_policy",
                path=["运维安全", "安全管理", "安全策略"],
                label="安全策略",
                aliases=["安全规范", "防护策略", "安全基线"],
                keywords=["安全", "策略", "防护", "漏洞", "基线", "加固"],
                negative_keywords=["品牌规范", "开发规范"],
                file_types=[".docx", ".pdf", ".md"],
            ),
            _label(
                label_id="ops.inspection_report",
                path=["运维安全", "巡检管理", "巡检报告"],
                label="巡检报告",
                aliases=["巡检记录", "巡检周报", "检查报告"],
                keywords=["巡检", "检查", "告警", "容量", "资源使用", "报告"],
                negative_keywords=["审计报告", "测试报告"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="ops.emergency",
                path=["运维安全", "应急管理", "应急预案"],
                label="应急预案",
                aliases=["应急响应", "故障预案", "灾备预案"],
                keywords=["应急", "预案", "响应", "灾备", "故障处置", "演练"],
                negative_keywords=["项目计划", "活动策划"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="ops.access_control",
                path=["运维安全", "账号权限", "权限管理"],
                label="权限管理",
                aliases=["账号权限", "访问控制", "账号申请"],
                keywords=["权限", "账号", "访问控制", "授权", "角色", "审批"],
                negative_keywords=["法务授权", "招聘"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
        ],
    },
    "project": {
        "display": "项目管理",
        "labels": [
            _label(
                label_id="project.plan",
                path=["项目管理", "计划管理", "项目计划"],
                label="项目计划",
                aliases=["实施计划", "推进计划", "项目排期"],
                keywords=["项目计划", "里程碑", "排期", "资源", "任务", "实施"],
                negative_keywords=["战略规划", "招聘计划"],
                file_types=[".docx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="project.status_report",
                path=["项目管理", "状态跟踪", "周报月报"],
                label="周报月报",
                aliases=["项目周报", "项目月报", "项目进展"],
                keywords=["周报", "月报", "进展", "风险", "状态", "里程碑"],
                negative_keywords=["销售月报", "财务月报"],
                file_types=[".docx", ".pptx", ".pdf"],
            ),
            _label(
                label_id="project.minutes",
                path=["项目管理", "沟通协同", "会议纪要"],
                label="会议纪要",
                aliases=["讨论纪要", "同步纪要", "项目纪要"],
                keywords=["会议纪要", "讨论", "决议", "行动项", "同步", "纪要"],
                negative_keywords=["拜访记录", "投诉记录"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="project.risk_list",
                path=["项目管理", "风险管理", "风险清单"],
                label="风险清单",
                aliases=["风险台账", "问题清单", "风险跟踪"],
                keywords=["风险", "问题", "阻塞", "依赖", "清单", "缓解措施"],
                negative_keywords=["缺陷报告", "投诉记录"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
            _label(
                label_id="project.retrospective",
                path=["项目管理", "复盘管理", "复盘总结"],
                label="复盘总结",
                aliases=["项目复盘", "结项复盘", "经验总结"],
                keywords=["复盘", "总结", "经验", "改进", "教训", "回顾"],
                negative_keywords=["故障复盘", "审计报告"],
                file_types=[".docx", ".pptx", ".pdf"],
            ),
            _label(
                label_id="project.milestone",
                path=["项目管理", "计划管理", "里程碑计划"],
                label="里程碑计划",
                aliases=["关键节点计划", "里程碑排期", "节点计划"],
                keywords=["里程碑", "节点", "关键路径", "排期", "交付点", "里程碑计划"],
                negative_keywords=["战略规划", "预算"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
        ],
    },
    "admin": {
        "display": "行政办公",
        "labels": [
            _label(
                label_id="admin.notice",
                path=["行政办公", "日常办公", "通知公告"],
                label="通知公告",
                aliases=["内部通知", "行政公告", "通告"],
                keywords=["通知", "公告", "通告", "全员", "安排", "要求"],
                negative_keywords=["市场方案", "发布说明"],
                file_types=[".docx", ".pdf", ".html"],
            ),
            _label(
                label_id="admin.meeting_schedule",
                path=["行政办公", "会议管理", "会议安排"],
                label="会议安排",
                aliases=["会议通知", "会议日程", "会务安排"],
                keywords=["会议", "安排", "日程", "会务", "参会", "议程"],
                negative_keywords=["会议纪要", "拜访记录"],
                file_types=[".docx", ".pdf", ".xlsx"],
            ),
            _label(
                label_id="admin.seal_request",
                path=["行政办公", "行政审批", "用印申请"],
                label="用印申请",
                aliases=["盖章申请", "印章审批", "用章申请"],
                keywords=["用印", "盖章", "印章", "审批", "合同盖章", "公章"],
                negative_keywords=["法务审查", "发票"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="admin.travel_request",
                path=["行政办公", "差旅管理", "差旅申请"],
                label="差旅申请",
                aliases=["出差申请", "出行审批", "差旅单"],
                keywords=["差旅", "出差", "机票", "酒店", "申请", "审批"],
                negative_keywords=["差旅报销", "费用报销"],
                file_types=[".docx", ".pdf", ".xlsx"],
            ),
            _label(
                label_id="admin.office_policy",
                path=["行政办公", "制度规范", "办公制度"],
                label="办公制度",
                aliases=["行政制度", "办公规范", "管理制度"],
                keywords=["制度", "办公", "规范", "行政", "考勤", "管理办法"],
                negative_keywords=["合规制度", "开发规范"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="admin.asset",
                path=["行政办公", "资产管理", "办公资产"],
                label="办公资产",
                aliases=["固定资产", "设备台账", "资产清单"],
                keywords=["资产", "设备", "领用", "归还", "台账", "办公用品"],
                negative_keywords=["入库验收", "采购需求"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
        ],
    },
    "strategy": {
        "display": "战略经营",
        "labels": [
            _label(
                label_id="strategy.planning",
                path=["战略经营", "战略规划", "战略规划"],
                label="战略规划",
                aliases=["发展规划", "年度战略", "中长期规划"],
                keywords=["战略", "规划", "发展方向", "目标", "路径", "布局"],
                negative_keywords=["项目计划", "活动计划"],
                file_types=[".pptx", ".docx", ".pdf"],
            ),
            _label(
                label_id="strategy.business_plan",
                path=["战略经营", "经营规划", "商业计划"],
                label="商业计划",
                aliases=["BP", "商业方案", "business plan"],
                keywords=["商业计划", "BP", "收入模型", "市场机会", "增长", "测算"],
                negative_keywords=["销售方案", "报价单"],
                file_types=[".pptx", ".docx", ".pdf"],
            ),
            _label(
                label_id="strategy.feasibility",
                path=["战略经营", "项目评估", "可行性报告"],
                label="可行性报告",
                aliases=["可研报告", " feasibility ", "可行性分析"],
                keywords=["可行性", "可研", "投入产出", "风险分析", "资源评估", "方案比较"],
                negative_keywords=["测试报告", "审计报告"],
                file_types=[".docx", ".pdf", ".pptx"],
            ),
            _label(
                label_id="strategy.project_initiation",
                path=["战略经营", "项目评估", "立项报告"],
                label="立项报告",
                aliases=["立项申请", "项目立项", "项目建议书"],
                keywords=["立项", "申请", "项目背景", "目标", "投入", "必要性"],
                negative_keywords=["采购申请", "招聘需求"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="strategy.operating_review",
                path=["战略经营", "经营分析", "经营分析"],
                label="经营分析",
                aliases=["经营复盘", "经营报告", "经营回顾"],
                keywords=["经营", "收入", "成本", "利润", "增长", "分析"],
                negative_keywords=["财务月报", "销售月报"],
                file_types=[".pptx", ".xlsx", ".pdf"],
            ),
            _label(
                label_id="strategy.investment",
                path=["战略经营", "投融资管理", "业务测算"],
                label="业务测算",
                aliases=["投资测算", "收益测算", "财务模型"],
                keywords=["测算", "投资", "回报", "IRR", "NPV", "收益模型"],
                negative_keywords=["报销", "发票"],
                file_types=[".xlsx", ".pptx", ".pdf"],
            ),
        ],
    },
    "audit": {
        "display": "风控审计",
        "labels": [
            _label(
                label_id="audit.audit_report",
                path=["风控审计", "审计管理", "审计报告"],
                label="审计报告",
                aliases=["内审报告", "审计结论", "专项审计"],
                keywords=["审计", "报告", "发现", "整改建议", "审计结论", "问题"],
                negative_keywords=["质量报告", "分析报告"],
                file_types=[".docx", ".pdf", ".pptx"],
            ),
            _label(
                label_id="audit.risk_policy",
                path=["风控审计", "风险管理", "风控制度"],
                label="风控制度",
                aliases=["风险制度", "风控规范", "风险政策"],
                keywords=["风控", "风险", "制度", "控制点", "审批要求", "管理办法"],
                negative_keywords=["办公制度", "合规制度"],
                file_types=[".docx", ".pdf"],
            ),
            _label(
                label_id="audit.working_papers",
                path=["风控审计", "审计执行", "内审底稿"],
                label="内审底稿",
                aliases=["审计底稿", "工作底稿", "底稿资料"],
                keywords=["底稿", "抽样", "凭证", "审计程序", "检查记录", "证据"],
                negative_keywords=["发票台账", "测试用例"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
            _label(
                label_id="audit.control_test",
                path=["风控审计", "内控评估", "控制测试"],
                label="控制测试",
                aliases=["内控测试", "控制点测试", "流程测试"],
                keywords=["控制测试", "内控", "流程测试", "控制点", "样本", "有效性"],
                negative_keywords=["功能测试", "回归测试"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
            _label(
                label_id="audit.issue_tracking",
                path=["风控审计", "整改管理", "问题整改"],
                label="问题整改",
                aliases=["整改跟踪", "整改计划", "问题闭环"],
                keywords=["整改", "问题闭环", "整改计划", "责任人", "完成时限", "跟踪"],
                negative_keywords=["项目风险", "bug修复"],
                file_types=[".xlsx", ".docx", ".pdf"],
            ),
            _label(
                label_id="audit.compliance_review",
                path=["风控审计", "合规检查", "合规检查"],
                label="合规检查",
                aliases=["稽核检查", "合规审查", "专项检查"],
                keywords=["合规检查", "检查", "稽核", "现场检查", "违规", "整改"],
                negative_keywords=["法务审查", "合同审查"],
                file_types=[".docx", ".pdf"],
            ),
        ],
    },
}


def get_all_labels() -> list[dict]:
    """返回所有叶子标签的扁平列表"""
    labels: list[dict] = []
    for domain in TAXONOMY.values():
        labels.extend(domain.get("labels", []))
    return labels


def get_label_by_id(label_id: str) -> dict | None:
    """根据 id 查找标签"""
    for label in get_all_labels():
        if label.get("id") == label_id:
            return label
    return None


def search_by_keyword(
    text: str,
    top_k: int = 10,
    filename_text: str = "",
) -> list[tuple[dict, float]]:
    """
    简单关键词命中打分，返回 (label_dict, score) 列表，按 score 降序。

    Score 规则：
    - 每命中一个 keywords 词 +1.0
    - 每命中一个 aliases 词 +0.8
    - 每命中一个 negative_keywords 词 -2.0
    - 文件名/路径包含相关词额外 +0.5（由调用方通过 filename_text 传入，可选）
    """
    if top_k <= 0:
        return []

    normalized_text = str(text or "").lower()
    normalized_filename = str(filename_text or "").lower()
    scored: list[tuple[dict, float]] = []

    for label in get_all_labels():
        score = 0.0

        for keyword in label.get("keywords", []):
            if keyword and keyword.lower() in normalized_text:
                score += 1.0

        for alias in label.get("aliases", []):
            if alias and alias.lower() in normalized_text:
                score += 0.8

        for negative in label.get("negative_keywords", []):
            if negative and negative.lower() in normalized_text:
                score -= 2.0

        if normalized_filename:
            related_terms = {
                label.get("label", ""),
                *label.get("aliases", []),
                *label.get("keywords", []),
                *label.get("path", [])[1:],
            }
            if any(term and term.lower() in normalized_filename for term in related_terms):
                score += 0.5

        if score > 0:
            scored.append((label, score))

    scored.sort(key=lambda item: (-item[1], item[0].get("id", "")))
    return scored[:top_k]


__all__ = [
    "TAXONOMY",
    "get_all_labels",
    "get_label_by_id",
    "search_by_keyword",
]
